import { RsvpCount } from './aggregate';

import { summarizeResponses } from './aggregate';

import Debug from 'debug';

const debug = Debug('demo');

const venues = [
  {
    name: 'Bob\'s Big Tent',
    address: '1234 Some Place, Anytown'
  },
  {
    name: 'The Grotto',
    address: '112 Boogey Woogey Ave, Overthere'
  },
];

const interestResponses = [
  [ // 0
    { name: 'Adam',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Alvin',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Arnie',
      section: 'Alto',
      rsvp: 0,
    },
    { name: 'Beth',
      section: 'Bass',
      rsvp: -1,
    },
    { name: 'Carlos',
      section: 'Conductor',
      rsvp: 1,
    },
    { name: 'Susan',
      section: 'Soprano',
      rsvp: 1,
    },
    { name: 'Ted',
      section: 'Tenor',
      rsvp: 1,
    },
    { name: 'Theodore',
      section: 'Tenor',
      rsvp: 0,
    },
  ],
  [ // 1
    { name: 'Adam',
      section: 'Alto',
      rsvp: -1,
    },
    { name: 'Alvin',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Arnie',
      section: 'Alto',
      rsvp: 0,
    },
    { name: 'Beth',
      section: 'Bass',
      rsvp: 1,
    },
    { name: 'Carlos',
      section: 'Conductor',
      rsvp: 1,
    },
    { name: 'Susan',
      section: 'Soprano',
      rsvp: 1,
    },
    { name: 'Ted',
      section: 'Tenor',
      rsvp: 1,
    },
    { name: 'Theodore',
      section: 'Tenor',
      rsvp: 1,
    },
  ],
  [ // 2
    { name: 'Adam',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Alvin',
      section: 'Alto',
      rsvp: 0,
    },
    { name: 'Arnie',
      section: 'Alto',
      rsvp: -1,
    },
    { name: 'Carlos',
      section: 'Conductor',
      rsvp: 1,
    },
    { name: 'Susan',
      section: 'Soprano',
      rsvp: 1,
    },
    { name: 'Theodore',
      section: 'Tenor',
      rsvp: 0,
    },
  ],
  [ // 3
    { name: 'Adam',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Alvin',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Arnie',
      section: 'Alto',
      rsvp: 1,
    },
    { name: 'Beth',
      section: 'Bass',
      rsvp: 0,
    },
    { name: 'Carlos',
      section: 'Conductor',
      rsvp: -1,
    },
    { name: 'Susan',
      section: 'Soprano',
      rsvp: 1,
    },
    { name: 'Ted',
      section: 'Tenor',
      rsvp: 0,
    },
    { name: 'Theodore',
      section: 'Tenor',
      rsvp: 0,
    },
  ],
];

function getInterestResponse(dateTimeId: number) {
  debug('getInterestResponse', dateTimeId);
  return Promise.resolve(interestResponses[dateTimeId-1]);
}


export const demoConfig = {
  getEventsP: Promise.resolve([
    {
      descriptionMd: 'We\'ll perform all the **greatest** hits and misses of the Orangatan Oboe Orchestra.\n\nBring your own snacks.',
      name: 'The Festivalissimo!',
      venue: venues[0],
      dateTimes: [
        { id: 1,
          hhmm: '16:15',
          yyyymmdd: '2022-05-13',
          duration: '60m',
          rsvp: 0,
          rsvpCount: summarizeResponses(interestResponses[0]),
        },
        { id: 2,
          hhmm: '15:15',
          yyyymmdd: '2022-05-14',
          duration: '60m',
          rsvp: 1,
          rsvpCount: summarizeResponses(interestResponses[1]),
        },
      ],
      getInterestResponse,
    },
    {
      descriptionMd: 'More **greatest** hits and misses?\n\nBring snacks for the audience.',
      name: 'A Rerun',
      venue: venues[1],
      dateTimes: [
        { id: 3,
          hhmm: '17:00',
          yyyymmdd: '2022-06-04',
          duration: '60m',
          rsvp: -1,
          rsvpCount: summarizeResponses(interestResponses[2]),
        },
        { id: 4,
          hhmm: '18:00',
          yyyymmdd: '2022-06-05',
          duration: '60m',
          rsvp: -1,
          rsvpCount: summarizeResponses(interestResponses[3]),
        },
      ],
      getInterestResponse,
    }
  ]),
};
